name: Build Mobile-Control-Core

on: push

jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - name: Get branch name
        id: get_branch
        run: |
          branch=${GITHUB_REF#refs/heads/}
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "prerelease=${branch//\//-}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: Replace branch name in .releaserc.json
        if: steps.get_branch.outputs.branch != 'main'
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "replace-me-feature-branch"
          replace: "${{ steps.get_branch.outputs.branch }}"
          include: ".releaserc.json"
      - name: Replace prerelease name in .releaserc.json
        if: steps.get_branch.outputs.branch != 'main'
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "replace-me-prerelease"
          replace: "${{ steps.get_branch.outputs.prerelease }}"
          include: ".releaserc.json"
      - name: install packages
        run: npm ci
      - name: build
        run: npm run build
      - name: Deploy to npm
        run: |
          DEBUG=semantic-release:* npx --package=semantic-release \
          --package=@semantic-release/commit-analyzer \
          --package=@semantic-release/release-notes-generator \
          --package=@semantic-release/changelog \
          --package=@semantic-release/exec \
          --package=conventional-changelog-conventionalcommits \
          --package=@semantic-release/npm \
          --package=@semantic-release/github \
          -- semantic-release --debug
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
